// <auto-generated />
namespace AspNet_WebApi.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Adiciona_Produtos : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Adiciona_Produtos));
        
        string IMigrationMetadata.Id
        {
            get { return "201808111758562_Adiciona_Produtos"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
